name: Build and Push Nix Docker Images

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  isopistekortti:
    name: Build & Push isopistekortti
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build isopistekortti Docker image
        run: nix build .#docker

      - name: Load image into Docker
        run: docker load < result

      - name: Tag image
        run: docker tag isopistekortti ghcr.io/tietokilta/isopistekortti:${{ github.sha }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/tietokilta/isopistekortti:${{ github.sha }}
